In [2]:
import pandas as pd
import numpy as np

train_df = pd.read_csv("train.csv")
test_df = pd.read_csv("test.csv")

print("train shape:", train_df.shape)
print("test shape:", test_df.shape)

display(train_df.head())
display(test_df.head())

train shape: (39073, 15)
test shape: (9769, 14)

,id,age,workclass,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,37194,50,Private,Masters,14,Divorced,Prof-specialty,Not-in-family,White,Female,0,0,35,United-States,<=50K
1,31094,28,Private,Some-college,10,Never-married,Exec-managerial,Not-in-family,White,Female,0,0,40,United-States,<=50K
2,33815,29,Private,HS-grad,9,Married-civ-spouse,Other-service,Wife,White,Female,0,1902,35,United-States,>50K
3,14501,32,Private,HS-grad,9,Never-married,Adm-clerical,Not-in-family,White,Female,0,0,40,United-States,<=50K
4,23400,62,State-gov,HS-grad,9,Married-civ-spouse,Transport-moving,Husband,White,Male,0,0,40,United-States,<=50K

,id,age,workclass,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country
0,7763,28,Private,Some-college,10,Never-married,Other-service,Not-in-family,Black,Male,0,0,40,United-States
1,23882,62,NaN,HS-grad,9,Married-civ-spouse,NaN,Husband,White,Male,0,0,40,United-States
2,30508,46,Self-emp-not-inc,Bachelors,13,Never-married,Prof-specialty,Not-in-family,Black,Male,0,0,23,United-States
3,28912,39,Private,Prof-school,15,Never-married,Prof-specialty,Not-in-family,White,Female,14084,0,35,United-States
4,19485,21,State-gov,Some-college,10,Never-married,Other-service,Own-child,White,Female,0,0,25,United-States

In [3]:
print("train shape:", train_df.shape)
print("test shape:", test_df.shape)

print("\n[train info]")
train_df.info()

print("\n[test info]")
test_df.info()

train shape: (39073, 15)
test shape: (9769, 14)

[train info]
<class 'pandas.DataFrame'>
RangeIndex: 39073 entries, 0 to 39072
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              39073 non-null  int64
 1   age             39073 non-null  int64
 2   workclass       36860 non-null  str
 3   education       39073 non-null  str
 4   education_num   39073 non-null  int64
 5   marital_status  39073 non-null  str
 6   occupation      36850 non-null  str
 7   relationship    39073 non-null  str
 8   race            39073 non-null  str
 9   sex             39073 non-null  str
 10  capital_gain    39073 non-null  int64
 11  capital_loss    39073 non-null  int64
 12  hours_per_week  39073 non-null  int64
 13  native_country  38395 non-null  str
 14  income          39073 non-null  str
dtypes: int64(6), str(9)
memory usage: 4.5 MB

[test info]
<class 'pandas.DataFrame'>
RangeIndex: 9769 entries, 0 to 9768
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              9769 non-null   int64
 1   age             9769 non-null   int64
 2   workclass       9183 non-null   str
 3   education       9769 non-null   str
 4   education_num   9769 non-null   int64
 5   marital_status  9769 non-null   str
 6   occupation      9183 non-null   str
 7   relationship    9769 non-null   str
 8   race            9769 non-null   str
 9   sex             9769 non-null   str
 10  capital_gain    9769 non-null   int64
 11  capital_loss    9769 non-null   int64
 12  hours_per_week  9769 non-null   int64
 13  native_country  9590 non-null   str
dtypes: int64(6), str(8)
memory usage: 1.0 MB

In [4]:
print("[train missing values]")
print(train_df.isnull().sum())

print("\n[test missing values]")
print(test_df.isnull().sum())

[train missing values]
id                   0
age                  0
workclass         2213
education            0
education_num        0
marital_status       0
occupation        2223
relationship         0
race                 0
sex                  0
capital_gain         0
capital_loss         0
hours_per_week       0
native_country     678
income               0
dtype: int64

[test missing values]
id                  0
age                 0
workclass         586
education           0
education_num       0
marital_status      0
occupation        586
relationship        0
race                0
sex                 0
capital_gain        0
capital_loss        0
hours_per_week      0
native_country    179
dtype: int64

In [5]:
for col in train_df.columns:
    if train_df[col].dtype == "object":
        print(col, ":", (train_df[col] == "?").sum())

In [6]:
cat_cols = [
    'workclass',
    'education',
    'marital_status',
    'occupation',
    'relationship',
    'race',
    'sex',
    'native_country'
]

for col in cat_cols:
    mode_value = train_df[col].mode()[0]
    train_df[col] = train_df[col].fillna(mode_value)
    test_df[col] = test_df[col].fillna(mode_value)

print("[train missing after fill]")
print(train_df.isnull().sum())

print("\n[test missing after fill]")
print(test_df.isnull().sum())

[train missing after fill]
id                0
age               0
workclass         0
education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
dtype: int64

[test missing after fill]
id                0
age               0
workclass         0
education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
dtype: int64

In [7]:
y_train = train_df["income"].map({
    "<=50K": 0,
    ">50K": 1
})

print(y_train.value_counts())

income
0    29729
1     9344
Name: count, dtype: int64

In [9]:
train_features = train_df.drop(columns=["income"])
test_features = test_df.copy()

full_df = pd.concat([train_features, test_features], axis=0)

full_encoded = pd.get_dummies(full_df, columns=cat_cols)

X_train = full_encoded.iloc[:len(train_df)]
X_test = full_encoded.iloc[len(train_df):]

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)

X_train shape: (39073, 105)
X_test shape: (9769, 105)

In [10]:
display(X_train.head())
display(y_train.head())

,id,age,education_num,capital_gain,capital_loss,hours_per_week,workclass_Federal-gov,workclass_Local-gov,workclass_Never-worked,workclass_Private,...,native_country_Portugal,native_country_Puerto-Rico,native_country_Scotland,native_country_South,native_country_Taiwan,native_country_Thailand,native_country_Trinadad&Tobago,native_country_United-States,native_country_Vietnam,native_country_Yugoslavia
0,37194,50,14,0,0,35,False,False,False,True,...,False,False,False,False,False,False,False,True,False,False
1,31094,28,10,0,0,40,False,False,False,True,...,False,False,False,False,False,False,False,True,False,False
2,33815,29,9,0,1902,35,False,False,False,True,...,False,False,False,False,False,False,False,True,False,False
3,14501,32,9,0,0,40,False,False,False,True,...,False,False,False,False,False,False,False,True,False,False
4,23400,62,9,0,0,40,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False

0    0
1    0
2    1
3    0
4    0
Name: income, dtype: int64

In [11]:
test_id = test_df["id"]

X_train.to_csv("X_train_preprocessed.csv", index=False)
X_test.to_csv("X_test_preprocessed.csv", index=False)
y_train.to_csv("y_train.csv", index=False)
test_id.to_csv("test_id.csv", index=False)